wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668730075.865089
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
architecture:
  desc: null
  value: GraphTransformer
batch_size:
  desc: null
  value: 2048
concat:
  desc: null
  value: false
dataset:
  desc: null
  value: NNN_v0
graphconv_dropout:
  desc: null
  value: 0.01507
hidden_channels:
  desc: null
  value: 81
learning_rate:
  desc: null
  value: 0.006226
linear_dropout:
  desc: null
  value: 0.4976
linear_hidden_channels:
  desc: null
  value:
  - 128
mode:
  desc: null
  value: val
n_epoch:
  desc: null
  value: 400
n_graphconv_layer:
  desc: null
  value: 7
n_linear_layer:
  desc: null
  value: 1
params:
  desc: null
  value:
  - dH
  - Tm
pooling:
  desc: null
  value: Set2Set
processing_steps:
  desc: null
  value: 5
